export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_LIST_TO_CART = "ADD_LIST_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const UPDATE_LIST_ITEMS = "UPDATE_LIST_ITEMS";