export const CREATE_OFFER_REQUEST = "CREATE_OFFER_REQUEST";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAIL = "CREATE_OFFER_FAIL";

export const ALL_OFFERS_REQUEST = "ALL_OFFERS_REQUEST";
export const ALL_OFFERS_SUCCESS = "ALL_OFFERS_SUCCESS";
export const ALL_OFFERS_FAIL = "ALL_OFFERS_FAIL";

export const UPDATE_OFFER_REQUEST = "UPDATE_OFFER_REQUEST";
export const UPDATE_OFFER_SUCCESS = "UPDATE_OFFER_SUCCESS";
export const UPDATE_OFFER_RESET = "UPDATE_OFFER_RESET";
export const UPDATE_OFFER_FAIL = "UPDATE_OFFER_FAIL";

export const UPDATE_OFFER_ACTIVATION_REQUEST = "UPDATE_OFFER_ACTIVATION_REQUEST";
export const UPDATE_OFFER_ACTIVATION_SUCCESS = "UPDATE_OFFER_ACTIVATION_SUCCESS";
export const UPDATE_OFFER_ACTIVATION_RESET = "UPDATE_OFFER_ACTIVATION_RESET";
export const UPDATE_OFFER_ACTIVATION_FAIL = "UPDATE_OFFER_ACTIVATION_FAIL";

export const UPDATE_OFFER_ACTIVATION_BY_ADMIN_REQUEST = "UPDATE_OFFER_ACTIVATION_BY_ADMIN_REQUEST";
export const UPDATE_OFFER_ACTIVATION_BY_ADMIN_SUCCESS = "UPDATE_OFFER_ACTIVATION_BY_ADMIN_SUCCESS";
export const UPDATE_OFFER_ACTIVATION_BY_ADMIN_RESET = "UPDATE_OFFER_ACTIVATION_BY_ADMIN_RESET";
export const UPDATE_OFFER_ACTIVATION_BY_ADMIN_FAIL = "UPDATE_OFFER_ACTIVATION_BY_ADMIN_FAIL";

export const DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_RESET = "DELETE_OFFER_RESET";
export const DELETE_OFFER_FAIL = "DELETE_OFFER_FAIL";

export const OFFER_DETAILS_REQUEST = "OFFER_DETAILS_REQUEST";
export const OFFER_DETAILS_SUCCESS = "OFFER_DETAILS_SUCCESS";
export const OFFER_DETAILS_FAIL = "OFFER_DETAILS_FAIL";

export const CLEAR_NEW_OFFER = "CLEAR_NEW_OFFER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";